/**
 * The expression operators.
 */
export const EXPRESSION_OPERATORS = [
  {
    name: 'abs',
    value: 'abs',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: 'ceil',
    value: 'ceil',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: 'cmp',
    value: 'cmp',
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: 'concat',
    value: 'concat',
    score: 1,
    meta: 'expr:string',
    version: '2.4.0',
  },
  {
    name: 'exp',
    value: 'exp',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$first',
    value: '$first',
    score: 1,
    meta: 'expr:array',
    version: '4.4.0',
  },
  {
    name: 'floor',
    value: 'floor',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: 'ifNull',
    value: 'ifNull',
    score: 1,
    meta: 'expr:cond',
    version: '2.2.0',
  },
  {
    name: 'in',
    value: 'in',
    score: 1,
    meta: 'expr:array',
    version: '3.4.0',
  },
  {
    name: 'isArray',
    value: 'isArray',
    score: 1,
    meta: 'expr:array',
    version: '3.2.0',
  },
  {
    name: 'isNumber',
    value: 'isNumber',
    score: 1,
    meta: 'expr:arith',
    version: '4.4.0',
  },
  {
    name: 'last',
    value: 'last',
    score: 1,
    meta: 'expr:array',
    version: '4.4.0',
  },
  {
    name: 'ln',
    value: 'ln',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: 'log',
    value: 'log',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$mod',
    value: '$mod',
    score: 1,
    meta: 'expr:arith',
    version: '2.2.0',
  },
  {
    name: 'xor',
    value: 'xor',
    score: 1,
    meta: 'expr:bool',
    version: '2.2.0',
  },
  {
    name: 'pow',
    value: 'pow',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: 'split',
    value: 'split',
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: 'sqrt',
    value: 'sqrt',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: 'strcasecmp',
    value: 'strcasecmp',
    score: 1,
    meta: 'expr:string',
    version: '2.2.0',
  },
  {
    name: 'substr',
    value: 'substr',
    score: 1,
    meta: 'expr:string',
    version: '2.2.0',
    deprecated: '3.4.0',
    replacement: '$substrBytes',
  },
  {
    name: 'trunc',
    value: 'trunc',
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
];
